# Generated by Django 4.1.4 on 2023-01-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=60)),
                ('tipo_transacao', models.BooleanField(default=1)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
