# Generated by Django 4.1.4 on 2023-01-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0002_delete_transacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dataCriacao', models.DateField()),
                ('orcamento', models.CharField(max_length=60)),
            ],
        ),
    ]
