# Generated by Django 4.1.4 on 2023-01-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='dataCriacao',
        ),
        migrations.AddField(
            model_name='budget',
            name='valor_limite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
