# Generated by Django 4.1.4 on 2023-01-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budget_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='valor_limite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
