# Generated by Django 4.1.5 on 2023-01-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category2',
        ),
    ]
