# Generated by Django 4.1.5 on 2023-01-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_delete_category2'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
