# Generated by Django 4.1.5 on 2023-01-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_category_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=60)),
                ('tipo_transacao', models.BooleanField(default=1)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
