# Generated by Django 4.1.5 on 2023-01-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_transacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
