# Generated by Django 4.1.3 on 2023-01-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_delete_transacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tipoTransacao',
            new_name='type_transaction',
        ),
        migrations.RemoveField(
            model_name='category',
            name='descricao',
        ),
    ]
