# Generated by Django 4.1.5 on 2023-01-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=60, null=True)),
                ('tipo_transacao', models.CharField(max_length=60, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
            ],
        ),
    ]
