# Generated by Django 4.1.5 on 2023-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=60, null=True)),
                ('tipo_transacao', models.BooleanField(default=1, null=True)),
                ('valor', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
