# Generated by Django 4.1.4 on 2023-01-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudTransacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
