# Generated by Django 4.1.4 on 2023-01-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudTransacao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person", name="age", field=models.IntegerField(default=0),
        ),
    ]
