# Generated by Django 4.1.5 on 2023-01-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudTransacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
