# Generated by Django 4.1.4 on 2023-01-29 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudTransacao', '0003_transacao_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='user_id',
            new_name='user',
        ),
    ]
