# Generated by Django 4.1.4 on 2023-01-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudTransacao", "0004_transacao"),
    ]

    operations = [
        migrations.RenameModel(old_name="Transacao", new_name="Tran",),
    ]
