# Generated by Django 4.1.4 on 2023-01-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudTransacao', '0004_alter_transacao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
