# Generated by Django 4.1.4 on 2023-01-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudTransacao", "0005_rename_transacao_tran"),
    ]

    operations = [
        migrations.DeleteModel(name="Tran",),
    ]
