# Generated by Django 4.1.4 on 2023-01-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudTransacao", "0006_delete_tran"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("descricao", models.CharField(max_length=60)),
                ("tipo_transacao", models.BooleanField(default=1)),
                ("valor", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(name="Person",),
    ]
