# Generated by Django 4.1.5 on 2023-01-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudTransacao', '0007_transacao_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
