# Generated by Django 4.1.5 on 2023-01-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudTransacao', '0010_alter_transacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
