# Generated by Django 4.1.5 on 2023-01-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudTransacao', '0011_alter_transacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.FloatField(default=0, null=True),
        ),
    ]
